# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KLrcCamera' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KLrcCamera
 
  pod 'DeviceKit', '~> 2.0'



  target 'KLrcCameraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KLrcCameraUITests' do
    # Pods for testing
  end

end
