# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'RealtimeMatte' do

  use_frameworks!
  pod 'MetalPetal'
  pod 'MetalPetal/Swift'
  pod 'VideoIO'

end
