# Uncomment the next line to define a global platform for your project
 platform :osx, '10.11'

target 'KYoutubeDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KYoutubeDemo
  #pod 'FacebookShare'
  #pod 'GoogleSignIn'
  pod 'GoogleAPIClientForREST/YouTube'
#  pod 'FBSDKCoreKit/Swift'
#  pod 'FBSDKLoginKit/Swift'
#  pod 'FBSDKShareKit/Swift'

  target 'KYoutubeDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KYoutubeDemoUITests' do
    # Pods for testing
  end

end
